version: '3.1'

services:
  joomla:
    image: joomla
    restart: always
    UPLOAD_LIMIT: 64M
    links:
      - joomladb:mysql
    ports:
      - 32761:80
    environment:
      JOOMLA_DATABASE_USER: bn_joomla
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: example

  joomladb:
    platform: linux/x86_64
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 14152:3306